Repository sogilis/Blog, pull requests merged in 2020-11, with the labels that each got.

#166 [Article] Une alternative à VueX
  site/content/posts/2020-11-06-vuex-alternative.md
  site/static/img/2020-08-31-vuex-alternative/app_screenshot.jpeg
  site/static/img/2020-08-31-vuex-alternative/title.jpeg
Labels: article

#200 [WIP][Article] UAS Cybersecurity
  site/content/posts/2020-10-27-uas_cybersecurity.md
  site/static/img/article_uas_cybersecurity/2020_10_27_cybersecurity.jpg
  site/static/img/article_uas_cybersecurity/uas_cybersecurity_001.png
  site/static/img/article_uas_cybersecurity/uas_cybersecurity_002.png
  site/static/img/article_uas_cybersecurity/uas_cybersecurity_003.png
  site/static/img/article_uas_cybersecurity/uas_cybersecurity_004.png
  site/static/img/article_uas_cybersecurity/uas_cybersecurity_005.png
  site/static/img/article_uas_cybersecurity/uas_cybersecurity_006.png
Labels: article

#220 chore: add alt image article in articles list
  site/themes/sogilis/layouts/_default/summary.html
Labels: chore

#216 doc: add tools for writing
  README.md
  docs/writing.md
Labels: doc

#219 fix indentation config for markdown files
  .editorconfig
Labels: chore
